<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Joshua Philipp Entrop" />

<meta name="date" content="2021-11-01" />

<title>{ExclusionTable} a package for keeping track of exclusions and inclusions</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">{ExclusionTable} a package for keeping
track of exclusions and inclusions</h1>
<h4 class="author">Joshua Philipp Entrop</h4>
<h4 class="date">2021-11-01</h4>



<p>In today’s blog post we will take a look at a package that allows you
to keep track of the number of observations that you in- or exclude from
your dataset or study population.</p>
<p>In epidemiological studies we often want to limit our study
population based on some inclusion and exclusion criteria. This is also
the case in other areas such as social science or econometrics. Although
there are a lot of nice functions in R to exclude observations from your
study population, i.e. in the packages <TT>{base}</TT>, <TT>{dplyr}</TT>
or <TT>{data.table}</TT>, there is no function that records how many
observations you excluded or included in each step. Hence, I created a
package <TT>{ExclusionTable}</TT> which includes the
<TT>exclusion_table()</TT> function that does exactly this. In this blog
post, I would like to introduce the function and show some of its
features. The blog post also serves as a vignette for the
<TT>{ExclusionTable}</TT> package.</p>
<p>For this let’s imagine we are working with data from the the US
National Health and Nutrition Examination Study (NHANES) from the years
2009 to 2012. This dataset includes questionnaire data on health related
topics for a sample of the US population. To load the data we can
conveniently use the <TT>{NHANES}</TT> package on CRAN. If you would
like to get more information on the dataset please take a look at
<TT>?NHANES</TT>.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(NHANES)         <span class="co"># NHANES dataset</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)          <span class="co"># Data manipulation</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(ExclusionTable)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="co"># Attach data</span></span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;NHANES&quot;</span>)</span></code></pre></div>
<p>Usually we don’t want to use the whole study population for our
analysis but only a subset. Let’s assume we are interested in a subset
of older females included in the NHANES dataset who have complete
information on BMI. For this we would like to include females aged 65
years or above and exclude all individuals with missing information on
BMI. If we would like to do this in <TT>R</TT> we could for example use
<TT>dplyr::filter()</TT>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># Subset NHANES data using dplyr::filter</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>NHANES_subset <span class="ot">&lt;-</span> NHANES <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>  <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">&quot;female&quot;</span>,</span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>         Age    <span class="sc">&gt;=</span> <span class="dv">65</span>,</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(BMI))</span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a><span class="co"># Print number of observations</span></span>
<span id="cb2-8"><a href="#cb2-8" tabindex="-1"></a><span class="fu">nrow</span>(NHANES_subset)</span></code></pre></div>
<pre><code>## [1] 731</code></pre>
<p>The code above obtained the subpopulation of the study population
that we are interest in. For this we excluded 9,269 of the 10,000
observations leaving us with 731 observations in the dataset. However,
we don’t know how many observations we excluded at each step, i.e. based
on each of the three criteria. Often we want to report those numbers in
our articles, e.g. in study population flow-charts. That’s were the
<TT>{ExclusionTable}</TT> package makes your life easier.</p>
<p>The <TT>ExclusionTable::exclusion_table()</TT> function takes as
first argument a dataframe and as second and third arguments a character
vector of inclusion and exclusion criteria, respectively. Let’s try this
function for our previous exclusions and inclusions. For this let’s set
<TT>keep_data = FALSE</TT>, since we are for now only interested in
obtaining the numbers of excluded individuals.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">exclusion_table</span>(NHANES,</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>                <span class="at">inclusion_criteria =</span> <span class="fu">c</span>(<span class="st">&quot;Gender == &#39;female&#39;&quot;</span>,</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>                                       <span class="st">&quot;Age    &gt;= 65&quot;</span>),</span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>                <span class="at">exclusion_criteria =</span> <span class="st">&quot;is.na(BMI)&quot;</span>,</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>                <span class="at">keep_data =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## ===============================================
## Excluded the following observations:
## ===============================================
## Exclusions based on INCLUSION criteria
## 
##            inclusion n_prior n_post n_excluded
## 1 Gender == &#39;female&#39;   10000   5020       4980
## 2       Age    &gt;= 65    5020    739       4281
## 3              TOTAL   10000    739       9261
## 
## Exclusions based on EXCLUSION criteria
## 
##    exclusion n_prior n_post n_excluded
## 1 is.na(BMI)     739    731          8
## 2      TOTAL     739    731          8
## 
## ===============================================</code></pre>
<p>The output above shows us that we excludes 4,980 male individuals
from our dataset and 4,281 individuals that were aged below 65. In total
we excluded 9,261 individuals based on our inclusion criteria.
Additionally, we excluded 8 individuals with missing information on BMI.
Hence, we end up with a dataset including 731 individuals as before.
Please notice the difference between inclusion and exclusion criteria:
Individuals who do not meet the inclusion criteria will be excluded
whereas individuals who meet the exclusion criteria will excluded. Also,
<TT>ExclusionTable::exclusion_table(}</TT> will always apply the
exclusion criteria after the inclusion criteria.</p>
<p>If we want to use strings in the filter statements, we can use single
quotation marks within the strings, e.g. <TT>“Gender ==
‘female’”</TT>.</p>
<p>This looks already really nice, but let’s improve the output a little
bit and supply some labels for our inclusion and exclusion criteria.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">exclusion_table</span>(NHANES,</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>                <span class="at">inclusion_criteria =</span> <span class="fu">c</span>(<span class="st">&quot;Gender == &#39;female&#39;&quot;</span>,</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>                                       <span class="st">&quot;Age    &gt;= 65&quot;</span>),</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                <span class="at">exclusion_criteria =</span> <span class="st">&quot;is.na(BMI)&quot;</span>,</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a>                <span class="at">labels_inclusion   =</span> <span class="fu">c</span>(<span class="st">&quot;Get females&quot;</span>,</span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a>                                       <span class="st">&quot;Age is &gt;= 65&quot;</span>),</span>
<span id="cb6-7"><a href="#cb6-7" tabindex="-1"></a>                <span class="at">labels_exclusion   =</span> <span class="st">&quot;Missing BMI&quot;</span>,</span>
<span id="cb6-8"><a href="#cb6-8" tabindex="-1"></a>                <span class="at">keep_data =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
## =========================================
## Excluded the following observations:
## =========================================
## Exclusions based on INCLUSION criteria
## 
##      inclusion n_prior n_post n_excluded
## 1  Get females   10000   5020       4980
## 2 Age is &gt;= 65    5020    739       4281
## 3        TOTAL   10000    739       9261
## 
## Exclusions based on EXCLUSION criteria
## 
##     exclusion n_prior n_post n_excluded
## 1 Missing BMI     739    731          8
## 2       TOTAL     739    731          8
## 
## =========================================</code></pre>
<p>Now we get nice labels in our inclusion and exclusion tables. Let’s
next actually keep the data and take a look at the output object of the
<TT>exclusion_table()</TT> function. For this we will set <TT>keep_data
= TRUE</TT>.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>NHANES_ex_tab <span class="ot">&lt;-</span> </span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>  <span class="fu">exclusion_table</span>(NHANES,</span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>                  <span class="at">inclusion_criteria =</span> <span class="fu">c</span>(<span class="st">&quot;Gender == &#39;female&#39;&quot;</span>,</span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>                                         <span class="st">&quot;Age    &gt;= 65&quot;</span>),</span>
<span id="cb8-5"><a href="#cb8-5" tabindex="-1"></a>                  <span class="at">exclusion_criteria =</span> <span class="st">&quot;is.na(BMI)&quot;</span>,</span>
<span id="cb8-6"><a href="#cb8-6" tabindex="-1"></a>                  <span class="at">labels_inclusion   =</span> <span class="fu">c</span>(<span class="st">&quot;Get females&quot;</span>,</span>
<span id="cb8-7"><a href="#cb8-7" tabindex="-1"></a>                                         <span class="st">&quot;Age is &gt;= 65&quot;</span>),</span>
<span id="cb8-8"><a href="#cb8-8" tabindex="-1"></a>                  <span class="at">labels_exclusion   =</span> <span class="st">&quot;Missing BMI&quot;</span>,</span>
<span id="cb8-9"><a href="#cb8-9" tabindex="-1"></a>                  <span class="at">keep_data =</span> <span class="cn">TRUE</span>)</span>
<span id="cb8-10"><a href="#cb8-10" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" tabindex="-1"></a><span class="co"># Print structure</span></span>
<span id="cb8-12"><a href="#cb8-12" tabindex="-1"></a><span class="fu">str</span>(NHANES_ex_tab, <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## List of 3
##  $ table_in:&#39;data.frame&#39;:    3 obs. of  4 variables:
##  $ table_ex:&#39;data.frame&#39;:    2 obs. of  4 variables:
##  $ dataset :&#39;data.frame&#39;:    731 obs. of  76 variables:
##  - attr(*, &quot;class&quot;)= chr &quot;exl_tbl&quot;</code></pre>
<p>The <TT>exclusion_table()</TT> function returns an <TT>exl_tbl</TT>
objects which is a list with maximum three <TT>data.frame</TT>s,
depending on the options used. The <TT>[[“table_in”]]</TT> and
<TT>[[“table_ex”]]</TT> <TT>data.frame</TT>s include the tables with the
numbers of individuals excluded due to our inclusion and exclusion
criteria, respectively. Those are the tables we have seen previously.
The <TT>[[“dataset”]]</TT> <TT>data.frame</TT> includes the cleaned
dataset without the excluded observations. You can use this dataset for
your further analysis. I usually assign the dataset to another object to
access it more easily.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>NAHANES_cleaned <span class="ot">&lt;-</span> NHANES_ex_tab[[<span class="st">&quot;dataset&quot;</span>]]</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a><span class="fu">nrow</span>(NAHANES_cleaned)</span></code></pre></div>
<pre><code>## [1] 731</code></pre>
<p>Sometimes you might also be interested in using a variable from your
global environment in the filter call. I often do this when I want to
filter certain diagnosis codes, that I stored in a character variable in
my environment. However, since we don’t have any diagnosis codes in this
dataset we will take a look at certain number of rooms in the
individual’s home. This information is stored in the variable
<TT>HomeRooms</TT>. Let’s assume we would like to only include
individuals who live in a home with 2, 4 and 9 rooms.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>room_selection <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">9</span>)</span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">exclusion_table</span>(NHANES,</span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>                <span class="at">inclusion_criteria =</span> <span class="fu">c</span>(<span class="st">&quot;HomeRooms %in% obj$room_selection&quot;</span>),</span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>                <span class="at">labels_inclusion   =</span> <span class="fu">c</span>(<span class="st">&quot;2, 4, 9 rooms&quot;</span>),</span>
<span id="cb12-6"><a href="#cb12-6" tabindex="-1"></a>                <span class="at">obj =</span> <span class="fu">list</span>(<span class="at">room_selection =</span> room_selection))</span></code></pre></div>
<pre><code>## 
## ==========================================
## Excluded the following observations:
## ==========================================
## Exclusions based on INCLUSION criteria
## 
##       inclusion n_prior n_post n_excluded
## 1 2, 4, 9 rooms   10000   2283       7717
## 2         TOTAL   10000   2283       7717
## 
## ==========================================</code></pre>
<p>By supplying objects as names lists to the <TT>obj</TT> argument of
<TT>exclusion_table</TT> we can access them in our filter calls using
<TT>obj$&lt;name of your object&gt;</TT>.</p>
<p>To summaries the <TT>ExclusionTable::exclusion_table()</TT> function
allows you to easily keep track of your exclusion and inclusion criteria
and helps you to report how many individuals you excluded at each step.
If you have any questions or suggestions please write me an <a href="mailto:joshuaentrop@posteo.de">email</a> or contact me on <a href="https://twitter.com/entjos/">Twitter</a> or file an issue on <a href="https://github.com/entjos/ExclusionTable/">GitHub</a>.</p>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
